apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: src
  contents:
  - path: debs/wireguard
    http:
      # asset URL (required)
      # See version available at https://pkgs.org/search/?q=wireguard
      url: http://archive.ubuntu.com/ubuntu/pool/universe/w/wireguard/wireguard_1.0.20210914-1ubuntu2_all.deb
      # verification checksum (optional)
      sha256: "45c218ebf8b76862421efd865f940af6c25f7d7e0107a1b4f75a7c4e4da50afe"

  - path: debs/wireguard-tools
    http:
      url: http://archive.ubuntu.com/ubuntu/pool/main/w/wireguard/wireguard-tools_1.0.20210914-1ubuntu2_amd64.deb
      sha256: "76b69e4e8b76ebd981e423ab002826efda000cb42dea0683994fc2d323bc60aa"
